# NOTE: Generated By hrp v4.3.0, DO NOT EDIT!

import sys
import os

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from debugtalk import *


if __name__ == "__main__":
    import funppy
    funppy.register("unicode_escape_to_utf8", unicode_escape_to_utf8)
    funppy.register("url_encode", url_encode)
    funppy.serve()
